spring:
  application:
    name: api-gateway
  redis:
    client-name: ${spring.application.name}
    host: default-test-redis.wanshifu.com
    port: 6379
    password: tRedisW135
    database: 1
  cloud:
    gateway:
      routes:
        - id: user-app-api
          uri: http://test-user-app-api.wanshifu.com
          predicates:
            - Method=GET, POST
            - Path=/app/**
          filters:
            - Authorization=createOrder, deleteOrder
        - id: user-web-api
          uri: http://test-user-web-api.wanshifu.com
          predicates:
            - Method=GET, POST
            - Path=/web/**
server:
  port: 8888
logging:
  level:
    org:
      springframework:
        security: DEBUG