spring:
  application:
    name: api-gateway
  redis:
    client-name: ${spring.application.name}
    host: default-test-redis.wanshifu.com
    port: 6379
    password: redis@wanshifu2017.com
    database: 0
  cloud:
    gateway:
      routes:
        - id: user-app-api
          uri: http://test-user-app-api.wanshifu.com
          predicates:
            - Method=GET, POST
            - Path=/app/**
        - id: user-web-api
          uri: http://test-user-web-api.wanshifu.com
          predicates:
            - Method=GET, POST
            - Path=/web/**
server:
  port: 8888